---
abstract: 'PSGI adapter for CGI'
author:
  - 'Tokuhiro Matsuno <tokuhirom@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Emulate-PSGI
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Response: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
